image: reactoranime/test-docker

variables:
  WP_TESTS_ABSPATH: "/var/www/html/"

before_script:
  - composer install

test1:
  script:
    - phpunit --configuration=ci/phpunit.xml
  tags:
    - docker

test2:
  script:
    - phpunit --configuration=ci/phpunit-2.xml
  tags:
    - docker

test3:
  script:
    - phpunit --configuration=ci/phpunit-3.xml
  tags:
    - docker
