image: reactoranime/test-docker

before_script:
  - composer install

test1:
  script:
    - phpunit --configuration=ci/phpunit.xml
    - php ci/test-coverage.php
  tags:
    - docker

#test2:
#  script:
#    - phpunit --config=ci/phpunit-2.xml
#  tags:
#    - docker
#
#test3:
#  script:
#    - phpunit --config=ci/phpunit-3.xml
#  tags:
#    - docker
