image: wpbakery/ci-wordpress

stages:
  - deploy

#  - codestyle
# - test
codestyle:js:
  image: wpbakery/standardjs
  stage: codestyle
  except:
    - refactor
  script:
    - npm run standard
  tags:
    - docker

codestyle:php:pluginFile:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml plugin-wordpress.php
  tags:
    - docker

codestyle:php:bootstrap:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml bootstrap
  tags:
    - docker

codestyle:php:framework:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Framework
  tags:
    - docker

codestyle:php:helpers:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Helpers
  tags:
    - docker

codestyle:php:modules:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Modules
  tags:
    - docker

codestyle:php:application:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Application.php visualcomposer/Requirements.php
  tags:
    - docker

test:php:framework:
  stage: test
  script:
    - php ci/composer.phar install
    - php tools/php-composer/cli.php
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-framework-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:php:helpers:
  stage: test
  script:
    - php ci/composer.phar install
    - php tools/php-composer/cli.php
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-helpers-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:php:modules:
  stage: test
  script:
    - php ci/composer.phar install
    - php tools/php-composer/cli.php
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-modules-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

deploying:
  image: wpbakery/ci-wordpress-npm
  stage:  deploy
  script:
   - mkdir dist/
   - npm install
   - mkdir -p ~/.ssh
   - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
   - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
   - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
   - chmod 700 ~/.ssh/id_rsa
   - echo "$SSH_PRIVATE_KEY" >> id_rsa
   - chmod 700 id_rsa
   - node tools/vcwb-builder/builder.js plugin -p dist/
   - unzip dist/visualcomposer.zip -d dist/
   - echo "$CI_PROJECT_URL/builds/$CI_BUILD_ID/artifacts/file/visualcomposer.zip" > $CI_PROJECT_DIR/build.log
   - rsync -rav --delete -e 'ssh -i id_rsa' dist/visualcomposer webuser@188.226.252.114:/var/www/test-deploy/
  artifacts:
   name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
   expire_in: 7d
   paths:
    - dist/visualcomposer.zip
    - build.log
  tags:
   - docker
  only:
   - tags
   - triggers

#pushSlack:
#  image: wpbakery/ci-wordpress-npm
#  stage: push
#  script: "curl -X POST -H 'Content-type: application/json' --data \"{'text':'New build created for *$CI_PROJECT_PATH* ($CI_BUILD_REF_NAME) <$(cat build.log)|visualcomposer.zip>.'}\" $CI_SLACK_URL"
#  tags:
#    - docker
