image: reactoranime/test-docker

before_script:
  - composer install

test1:
  script:
    - ls -la
    - phpunit --configuration=ci/phpunit.xml --include-path="tests"
    - cat test.log
  tags:
    - docker

#test2:
#  script:
#    - phpunit --config=ci/phpunit-2.xml
#  tags:
#    - docker
#
#test3:
#  script:
#    - phpunit --config=ci/phpunit-3.xml
#  tags:
#    - docker
