image: wpbakery/ci-wordpress

stages:
  - codestyle
  - test

testJavascriptCS:
  image: wpbakery/standardjs
  stage: codestyle
  script:
    - standard
  tags:
    - docker

testPluginpCS:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - phpcs --standard=ci/ruleset.xml plugin-wordpress.php
  tags:
    - docker

testBootstrapCS:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - phpcs --standard=ci/ruleset.xml bootstrap
  tags:
    - docker

testFrameworkCS:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - phpcs --standard=ci/ruleset.xml visualcomposer/Framework
  tags:
    - docker

testHelpersCS:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - phpcs --standard=ci/ruleset.xml visualcomposer/Helpers
  tags:
    - docker

testModulesCS:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - phpcs --standard=ci/ruleset.xml visualcomposer/Modules
  tags:
    - docker

testApplicationCS:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - phpcs --standard=ci/ruleset.xml visualcomposer/Application.php visualcomposer/Requirements.php
  tags:
    - docker

testFramework:
  stage: test
  script:
    - composer install
    - phpunit --configuration=ci/phpunit-framework-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

testHelpers:
  stage: test
  script:
    - composer install
    - phpunit --configuration=ci/phpunit-helpers-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

# Disabled while not ready module tests
#testModules:
#  stage: test
#  script:
#    - composer install
#    - phpunit --configuration=ci/phpunit-modules-coverage.xml
#    - php ci/coverage-test.php
#  tags:
#    - docker

