image: wpbakery/ci-wordpress

stages:
  - codestyle
  - test
  - deploy
  - push

codestyle:js:
  image: wpbakery/standardjs
  stage: codestyle
  except:
    - refactor
    - headerFooter
  script:
    - npm run standard
  tags:
    - docker

codestyle:php:pluginFile:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml plugin-wordpress.php
  tags:
    - docker

codestyle:php:bootstrap:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml bootstrap
  tags:
    - docker

codestyle:php:framework:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Framework
  tags:
    - docker

codestyle:php:helpers:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Helpers
  tags:
    - docker

codestyle:php:modules:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Modules
  tags:
    - docker

codestyle:php:application:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Application.php visualcomposer/Requirements.php
  tags:
    - docker

test:php:framework:
  stage: test
  script:
    - php ci/composer.phar install
    - php tools/php-composer/cli.php
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-framework-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:php:helpers:
  stage: test
  script:
    - php ci/composer.phar install
    - php tools/php-composer/cli.php
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-helpers-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:php:modules:
  stage: test
  script:
    - php ci/composer.phar install
    - php tools/php-composer/cli.php
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-modules-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:js:build:
  stage: test
  image: node:9.11
  script:
    - npm install
    - npm run build
    - cat public/dist/front.bundle.js | grep "Cannot find module" && exit 1
    - cat public/dist/vendor.bundle.js | grep "Cannot find module" && exit 1
    - cat public/dist/pe.bundle.js | grep "Cannot find module" && exit 1
    - cat public/dist/wp.bundle.js | grep "Cannot find module" && exit 1
    - cat public/dist/wpPostRebuild.bundle.js | grep "Cannot find module" && exit 1
  tags:
    - docker

deployEditorsBundle:
  image: node:8.6.0
  stage: deploy
  script:
    - bash ci/deploy-editors-bundle.sh
  tags:
    - docker

deployAssetsBundle:
  image: node:8.6.0
  stage: deploy
  script:
    - bash ci/deploy-assets-bundle.sh
  tags:
    - docker
