image: wpbakery/ci-wordpress

stages:
  - codestyle
  - test
  - deploy

codestyle:js:
  image: wpbakery/standardjs
  stage: codestyle
  script:
    - npm run standard
  tags:
    - docker

codestyle:php:pluginFile:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml plugin-wordpress.php
  tags:
    - docker

codestyle:php:bootstrap:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml bootstrap
  tags:
    - docker

codestyle:php:framework:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Framework
  tags:
    - docker

codestyle:php:helpers:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Helpers
  tags:
    - docker

codestyle:php:modules:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Modules
  tags:
    - docker

codestyle:php:application:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml visualcomposer/Application.php visualcomposer/Requirements.php
  tags:
    - docker

test:php:framework:
  stage: test
  script:
    - php ci/composer.phar install
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-framework-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:php:helpers:
  stage: test
  script:
    - php ci/composer.phar install
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-helpers-coverage.xml
    - php ci/coverage-test.php
  tags:
    - docker

test:php:modules:
  stage: test
  script:
    - php ci/composer.phar install
    - php -d 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so' ci/phpunit-5.6.5.phar --configuration=ci/phpunit-modules-coverage.xml
    #- php ci/coverage-test.php
  tags:
    - docker

deploy:test:alpha:
  image: wpbakery/ci-deployer
  stage: deploy
  script:
    - cd ci/deploy/test && dep deploy test
  tags:
   - docker

